apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: mtk21/wordsmith-web:0a659a4dd00ce009847525152ec67bd724458e66
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: WORDS_HOST
              value: api
            - name: WORDS_PORT
              value: "8080"
            - name: WEB_PORT
              value: "8080"
