[wordsmith]
# Replace the IP below with your EC2 public IP after `terraform apply`,
# or generate this file dynamically in your own workflow.
wordsmith-server ansible_host=100.48.80.49

[wordsmith:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/laggylegend/Videos/cloud-project3/wordsmith/microservices-key.pem
ansible_python_interpreter=/usr/bin/python3
